import Head from 'next/head';
import {Fragment } from 'react';
import Header from '../components/Header/Header';
import MainContent from '../components/MainContent/MainContent';
import HomeBanner from '../components/HomeBanner/HomeBanner';
import Featured from '../components/Featured/Featured';
import FeaturedJob from '../components/FeaturedJob/FeaturedJob';
import Counter from '../components/Counter/Counter';
import NetellerNews from '../components/NetellerNews/NetellerNews';

import HomePage from '../components/HomePage/HomePage';
import DashboardPage from '../components/DashboardPage/DashboardPage';

export default function Home() {
  const logState = true;
  const renderApp = logState ? <HomePage /> : <DashboardPage />

  return (
    // renderApp
    <Fragment>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainContent />
      <HomeBanner />
      <Featured />
      <FeaturedJob />
      <Counter />
      <NetellerNews />
    </Fragment>
  )
}
