import Head from 'next/head';
import {Fragment } from 'react';
import { useState, useEffect } from 'react';
import Header from '../components/Header/Header';
import HomeBanner from '../components/HomeBanner/HomeBanner';
import Featured from '../components/Featured/Featured';
import FeaturedJob from '../components/FeaturedJob/FeaturedJob';
import Counter from '../components/Counter/Counter';
import NetellerNews from '../components/NetellerNews/NetellerNews';

import HomePage from '../components/HomePage/HomePage';
import DashboardPage from '../components/DashboardPage/DashboardPage';
import MainHeader from '../components/Header/MainHeader';

const Home = () => {
  const [isLoggedIn, setIsLoggedIn] = useState(false);

  useEffect(() => {
    setIsLoggedIn(window.localStorage.getItem("isLoggedIn"))
  
  }, [])
  // const logState = true;
  const renderApp = isLoggedIn ? <DashboardPage /> : <HomePage />

  return (
    // renderApp
    <Fragment>
      <Head>
        <title>Golobal Jobs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {renderApp}
    </Fragment>
  )
}

export default Home;