import Head from 'next/head';
import {Fragment } from 'react';
import MainContent from '../MainContent/MainContent';
import HomeBanner from '../HomeBanner/HomeBanner';
import Featured from '../Featured/FeaturedData';
import FeaturedJob from '../FeaturedJob/FeaturedJob';
import Counter from '../Counter/Counter';
// import NetellerNews from '../components/NetellerNews/NetellerNews';

export default function HomePage() {
    return (
      <Fragment>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <MainContent />
        <HomeBanner />
        <Featured />
        <FeaturedJob />
        <Counter />
        {/* <NetellerNews /> */}
      </Fragment>
    )
}